In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

# Cargamos los datos
data = pd.read_csv('C:/Users/PAOLOac/Desktop/Latam - Desafio/datos2.csv')
data = data.values
print(data)
hola = data[:1,0][0]
print(hola)

[[ 1  1  1 ...  1 34  0]
 [ 1  2  1 ...  1 34  0]
 [ 1  3  1 ...  1 34  0]
 ...
 [12  3  1 ...  1 28  1]
 [12  5  1 ...  1 28  0]
 [12  0  1 ...  1 28  0]]
1


In [2]:
# Separamos los datos en conjuntos de entrenamiento y prueba
train_size = int(0.8 * len(data))
train_data = data[:train_size]
test_data = data[train_size:]

In [3]:
# Separamos los datos de entrenamiento y prueba en características y etiquetas
train_features = train_data[:, :-1]
train_labels = train_data[:, -1:]
test_features = test_data[:, :-1]
test_labels = test_data[:, -1:]
print (train_features)

[[ 1  1  1  6  1 34]
 [ 1  2  1  6  1 34]
 [ 1  3  1  6  1 34]
 ...
 [10  1  1 13  0  7]
 [10  2  1 13  0  7]
 [10  3  1 13  0  7]]


In [4]:
# Definimos el modelo
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(32, activation='relu', input_shape=(train_features.shape[1],)),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1)
])
    # Compilamos el modelo
model.compile(optimizer='adam', loss='mse')

# Entrenamos el modelo
model.fit(train_features, train_labels, epochs=50, batch_size=32)

# Evaluamos el modelo en los datos de prueba
test_loss = model.evaluate(test_features, test_labels)
print(f'Pérdida en los datos de prueba: {test_loss:.4f}')

# Hacemos predicciones utilizando los datos de prueba
predictions = model.predict(test_features)


Epoch 1/50
1706/1706 [==============================] - 2s 833us/step - loss: 0.2848
Epoch 2/50
1706/1706 [==============================] - 1s 818us/step - loss: 0.1500
Epoch 3/50
1706/1706 [==============================] - 1s 819us/step - loss: 0.1492
Epoch 4/50
1706/1706 [==============================] - 1s 821us/step - loss: 0.1471
Epoch 5/50
1706/1706 [==============================] - 1s 825us/step - loss: 0.1475
Epoch 6/50
1706/1706 [==============================] - 1s 814us/step - loss: 0.1460
Epoch 7/50
1706/1706 [==============================] - 1s 831us/step - loss: 0.1454
Epoch 8/50
1706/1706 [==============================] - 1s 812us/step - loss: 0.1441
Epoch 9/50
1706/1706 [==============================] - 1s 830us/step - loss: 0.1433
Epoch 10/50
1706/1706 [==============================] - 1s 827us/step - loss: 0.1421
Epoch 11/50
1706/1706 [==============================] - 1s 817us/step - loss: 0.1422
Epoch 12/50
1706/1706 [==============================] - 1s 825

In [5]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Calcular MSE
mse = mean_squared_error(test_labels, predictions)

# Calcular R^2
r2 = r2_score(test_labels, predictions)

# Calcular MAE
mae = mean_absolute_error(test_labels, predictions)

In [6]:
print(mse)
print(r2)
print(mae)

0.17609509109254143
0.012612114026983035
0.3438984854254028
